[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-unknown-linux-gnu]
linker = "clang"

[target.x86_64-pc-windows-gnu]
linker = "clang"

[target.aarch64-pc-windows-gnullvm]
linker = "clang"

[target.x86_64-apple-darwin]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

[env]
CC = "clang"
